config/routes.rb
Hackernotes::Application.routes.draw do

  root :to => 'home#homepage'
  get 'search', :to => 'repositories#search'

  match '/auth/github/callback' => 'sessions#create', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match 'auth/failure', to: redirect('/')

  post '/create_note' => 'repositories#create_note'
  put '/vote' => 'votes#vote'
  delete '/remove' => 'remove#remove'

  get  ':owner/*name/*resource/*id', :to => 'notes#resource_iframe', :as => 'resource_iframe', :format => false
  get  ':owner/*name/*resource', :to => 'repositories#show_resources', :as => 'show_resources', :format => false
  get  ':owner/*name', :to => 'repositories#show', :as => 'show_repo', :format => false
#  get  ':username', :to => 'users#show', :as => 'user_profile', :format => false
end

app/models/repository.rb
class Repository
  include Mongoid::Document
  include Mongoid::Timestamps

  include Jimmy
  field :name
  field :owner
  field :full_name
  field :description
  field :watchers_count, type: Integer
  field :forks_count, type: Integer

  validates :name, :uniqueness => {:scope => :owner}

  after_create :create_from_service

  def create_from_service
    delay.create_blogs
    delay.create_slides
    # delay.create_tweeters
    delay.create_noteworthies
    delay.create_qnas
  end

  def owner?(user_name)
    owner == user_name
  end

  embeds_many :tweeters
  embeds_many :subscription_services
  embeds_many :blogs
  embeds_many :tips
  embeds_many :slides
  embeds_many :qnas
  embeds_many :books
  embeds_many :noteworthies
  embeds_many :screencasts
  embeds_many :talks
  embeds_many :tutorials
  embeds_many :examples
end

app/controllers/repositories_controller.rb
class RepositoriesController < RepositoriesBaseController

  def search
    @g_repos = GithubService.new.search(params[:q])
  end

  def show
    @repo = find_repo(params)
    popuplate_resources
  end

  def show_resources
    @repo = find_repo(params)
    @resources = @repo.send(params[:resource]).page params[:page]
    @menu = menu.compact
  end

  def create_note
    @repo = Repository.find(params[:id].keys.first)
    resource_type = params[:resource]
    @note = @repo.send(resource_type).new(url: params[:url], user: current_user)
    if @note.save
      flash[:notice] = "#{resource_type.singularize.capitalize} added!"
      current_user.reward_karma(:resource, @note)
      redirect_to show_repo_path({ owner: @repo.owner, name: @repo.name })
    else
      flash[:alert] = "Please resolve following errors and retry"
      popuplate_resources
      render :show
    end
  end

  private
  def popuplate_resources
    @talks = @repo.talks.limit(4)
    @tutorials = @repo.tutorials.limit(4)
    @examples = @repo.examples.limit(4)
    @tweeters = @repo.tweeters.limit(10)
    @books = @repo.books.limit(6)
    @subscription_services = @repo.subscription_services.limit(4)
    @blogs = @repo.blogs.limit(4)
    @tips = @repo.tips.limit(4)
    @slides = @repo.slides.limit(4)
    @qnas = @repo.qnas.limit(4)
    @noteworthies = @repo.noteworthies.limit(4)
    @screencasts = @repo.screencasts.limit(4)
  end

  def menu
    menu = [:talks, :blogs, :subscription_services, :screencasts, :tutorials, :examples, :slides, :tips, :qnas, :noteworthies]
    menu.map { |note| note if @repo.send(note).count > 0 }
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper

 NOTES = { 'Blogs' => 'blogs',
            'Subscribe' => 'subscription_services',
            "Tips n Tricks" => 'tips',
            'Slides' => 'slides',
            'Tutorials' => 'tutorials',
            'Examples' => 'examples',
            'QnA' => 'qnas',
            'Screencasts' => 'screencasts',
            'Talks' => 'talks',
            'Noteworthy' => 'noteworthies' }

  def title_link(repo)
    link_to repo.name.capitalize, show_repo_path(repo.owner, repo.name)
  end

  def title(resources)
    NOTES.invert[resource_name(resources)]
  end

  def resource_name(resources)
    resources.name.to_s.underscore.pluralize
  end

  def template(resources)
    resource_name = resource_name(resources)
    return 'media' if resource_name == 'slides' || resource_name == 'talks' || resource_name == 'screencasts'
    'resources'
  end

  def link_to_vote(resource, direction)
    link_to(image_tag("vote_#{direction}.png",
                       alt: "vote #{direction}"),
                       '#',
                       class: "vote vote#{direction.capitalize}",
                       'data-id' => resource.id,
                       'data-resource_type' => resource.model_name)
  end

  def link_to_remove_if_power_user(resource, repo)
    link_to(image_tag("delete.png", alt: "remove"),
            '#',
            class: "remove",
            'data-id' => resource.id,
            'data-resource_type' => resource.model_name) if current_user && current_user.power_user?(repo.owner)
  end

  def description(repo)
    "#{repo.description}<br/>Created by: <b>#{repo.owner}</b>".html_safe
  end

  def sidebar(resources, title)
    return nil if resources.empty?
    anchor = resources.first.model_name.underscore.pluralize
    { anchor: "##{anchor}", title: title }
  end

end

app/views/repositories/_media.html.haml
%section{id: id, class: 'clearfix'}
  - if title
    %a{href: show_resources_path(owner: @repo.owner, name: @repo.name, resource: id)}
      %h2= title
    %br
  - resources.each do |r|
    - next if r.title.nil?
    %div.box.resource
      %h3.title
        = link_to(truncate(r.title, length: 50).html_safe, r.url)
        %span.voteContainer.hidden
          = link_to_vote(r, :up)
          %span= r.votes_count
          = link_to_vote(r, :down)
        %span
          = link_to_remove_if_power_user(r, @repo)
      %p
        = link_to image_tag(r.thumbnail_url),
          resource_iframe_path(owner: @repo.owner, name: @repo.name, resource: media, id: r.id),
          { 'data-fancybox-type' => 'iframe', class: 'fancybox' } if r.thumbnail_url.present?
        %br
        = truncate(r.description.html_safe, length: 110) if r.description.present?
%hr

app/views/repositories/_note_form.html.haml
- notes = { 'Blog' => 'blogs',
            'Talk' => 'talks',
            'Tutorial' => 'tutorials',
            'Example' => 'examples',
            'Subscribe' => 'subscription_services',
            "Tips n Tricks" => 'tips',
            'Slide' => 'slides',
            'QnA' => 'qnas',
            'Screencast' => 'screencasts',
            'Tweeter' => 'tweeters',
            'Book' => 'books',
            'Noteworthy' => 'noteworthies' }

%h3
  %label{for: 'url'} Share a link
= form_tag(create_note_path, method: 'post') do
  = success_message
  = text_field_tag 'url', @note.try(:url), placeholder: 'Enter Resource URL', required: true
  = hidden_field :id, @repo.id
  = select_tag 'resource', options_for_select(notes), class: 'fancySelectBox hidden'
  = submit_tag 'add', class: 'button'
  = render :partial => 'shared/errors', :locals => {:model => @note} if @note
%div#suggestion

app/views/repositories/_notes.html.haml
- if @noteworthies.empty?
  %p.notification
    Looks like 
    = link_to "Jimmy", "https://github.com/JimmyHackerNotes"
    is working hard gathering resources, 
    meanwhile you can add your own or 
    = link_to "refresh"
    the page to see the newly added ones.

- if @tweeters.present?
  %section#tweeters.clearfix
    - @tweeters.each do |t|
      - next if t.thumbnail_url.blank?
      = link_to(image_tag(t.thumbnail_url, alt: t.title), t.url)
    %hr

- if @books.present?
  %section#books.clearfix
    - @books.each do |b|
      - next if b.thumbnail_url.blank?
      = link_to(image_tag(b.thumbnail_url, alt: b.title), b.url)
    %hr

%section#note_form.clearfix
  = render 'note_form'
  %hr

= render 'media', resources: @talks, id: 'talks', title: 'Talks', media: 'talks' unless @talks.empty?
= render 'resources', resources: @blogs, id: 'blogs', title: 'Blogs' unless @blogs.empty?
= render 'resources', resources: @subscription_services, id: 'subscription_services', title: 'Subscribe' unless @subscription_services.empty?
= render 'media', resources: @screencasts, id: 'screencasts', title: 'Screencasts', media: 'screencasts' unless @screencasts.empty?
= render 'resources', resources: @tutorials, id: 'tutorials', title: 'Tutorials' unless @tutorials.empty?
= render 'resources', resources: @examples, id: 'examples', title: 'Examples' unless @examples.empty?
= render 'media', resources: @slides, id: 'slides', title: 'Slides', media: 'slides' unless @slides.empty?
= render 'resources', resources: @tips, id: 'tips', title: 'Tips n Tricks' unless @tips.empty?
= render 'resources', resources: @qnas, id: 'qnas', title: 'QnA' unless @qnas.empty?
= render 'resources', resources: @noteworthies, id: 'noteworthies', title: 'Noteworthy' unless @noteworthies.empty?

app/views/repositories/_resources.html.haml
%section{id: id, class: 'clearfix'}
  - if title
    %a{href: show_resources_path(owner: @repo.owner, name: @repo.name, resource: id)}
      %h2= title
  - resources.each do |r|
    - next if r.title.nil?
    %div.resource
      %h3.title
        = link_to(truncate(r.title, length: 60).html_safe, r.url)
        %span.voteContainer.hidden
          = link_to_vote(r, :up)
          %span= r.votes_count
          = link_to_vote(r, :down)
        %span
          = link_to_remove_if_power_user(r, @repo)
      %p
        = truncate(r.description.html_safe, length: 180) if r.description.present?
%hr

app/views/repositories/_sidebar.html.haml
- titles = [ sidebar(@talks, 'Talks'),
             sidebar(@blogs, 'Blogs'),
             sidebar(@subscription_services, 'Subscribe'),
             sidebar(@screencasts, 'Screencasts'),
             sidebar(@tutorials, 'Tutorials'),
             sidebar(@examples, 'Examples'),
             sidebar(@slides, 'Slides'),
             sidebar(@tips, "Tips 'n' Tricks"),
             sidebar(@qnas, 'QnA'),
             sidebar(@noteworthies, 'Noteworthy') ].compact

- title_values = titles.map { |t| t[:anchor].delete('#').titlecase }
- desc = title_values.join(', ').concat(" for #{@repo.name.capitalize}")
= page_description(desc)
= page_title "#{title_values.join(' | ')} for #{@repo.name.capitalize}"
= page_keywords "#{@repo.name}, Development, Learn, Software development, Web development, Programming, Code, #{title_values.join(', ')}"

%aside#sidebar
  %nav
    %span.logo#nav-logo
      %a{href: root_path}
        %span Hacker Notes
      %a{href: '#top'}
        = repo.name
    %ul
      - titles.each do |n|
        %li
          = link_to(n[:title], n[:anchor])
    %div.bg_bottom

app/views/repositories/_videos.html.haml
%section{id: id, class: 'clearfix'}
  %a{href: show_resources_path(owner: @repo.owner, name: @repo.name, resource: id)}
    %h2= title
  %br
  - resources.each do |r|
    %div.box.resource
      %h3.title
        = link_to(r.title.html_safe, r.url)
        %span.hidden.voteContainer
          = link_to_vote(r, :up)
          %span= r.votes_count
          = link_to_vote(r, :down)
      %p
        = link_to image_tag(r.thumbnail_url),
          resource_iframe_path(owner: @repo.owner, name: @repo.name, resource: 'videos', id: r.id),
          { 'data-fancybox-type' => 'iframe', class: 'fancybox' }
        %br
        = truncate(r.description.html_safe, length: 140)
%hr

app/views/repositories/search.html.erb
<p><%= render "shared/search_form" %></p>

<% @g_repos.each do |repo| %>
  <h2><%= title_link repo %></h2>
  <p><%= description repo %></p>
<% end %>

app/views/repositories/show.html.haml
- content_for :head do
  = stylesheet_link_tag "repo/repositories"

= render "shared/fork", name: @repo.name, owner: @repo.owner

- content_for :sidebar do
  = render "sidebar", repo: @repo

%a{href: "http://github.com/#{@repo.owner}/#{@repo.name}", target: "#{@repo.owner}/#{@repo.name}"}
  %h2.github-repo-name= @repo.name.capitalize
%p= @repo.description

%hr
= render "notes"

app/views/repositories/show_repo.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "repo/repositories"  %>
<% end %>

<% content_for :sidebar do %>
  <%= render "sidebar", repo: @repo %>
<% end %>

<h2><%= @repo.name.capitalize %></h2>
<p><%= @repo.description %></p>
<hr/>
<%= render "notes" %>

app/views/repositories/show_resources.html.haml
= page_title "#{title(@resources)} for #{@repo.name}"
= page_keywords "#{@repo.name}, Development, Learn, Software development, Web development, Programming, Code, #{title(@resources)}"
= page_description "#{title(@resources)} for #{@repo.name}"

= paginate @resources

%h2= title_link @repo
%nav.menu
  - @menu.each do |item|
    = link_to RepositoriesHelper::NOTES.invert[item.to_s],
      "/#{@repo.owner}/#{@repo.name}/#{item.to_s}"
%hr

- if @resources.present?
  = render template(@resources), resources: @resources, media: resource_name(@resources), id: nil, title: nil

= paginate @resources