config/routes.rb
Hackernotes::Application.routes.draw do

  root :to => 'home#homepage'
  get 'search', :to => 'repositories#search'

  match '/auth/github/callback' => 'sessions#create', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match 'auth/failure', to: redirect('/')

  post '/create_note' => 'repositories#create_note'
  put '/vote' => 'votes#vote'
  delete '/remove' => 'remove#remove'

  get  ':owner/*name/*resource/*id', :to => 'notes#resource_iframe', :as => 'resource_iframe', :format => false
  get  ':owner/*name/*resource', :to => 'repositories#show_resources', :as => 'show_resources', :format => false
  get  ':owner/*name', :to => 'repositories#show', :as => 'show_repo', :format => false
#  get  ':username', :to => 'users#show', :as => 'user_profile', :format => false
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
    @repos = Repository.desc(:created_at).limit(10)
    @popular_repos = Repository.desc(:watchers_count).limit(15)

    @karma_leaders = User.desc(:total_karma).limit(5)
  end

end

app/views/home/_leader_board.html.haml
%div.leaderBoard
  %div Leader Board
  %ul
    - @karma_leaders.each do |leader|
      %li
        = link_to image_tag(leader.image, alt: leader.name, size: '38x38'), "https://github.com/#{leader.nickname}"
        = (leader.name || leader.nickname).camelcase
        (
        = leader.total_karma
        )

app/views/home/_news.html.haml
%div.news
  %p
    = link_to image_tag("ruby_logo.png", size: "54x54"), show_repo_path(owner: 'ruby', name: 'ruby')
    %div Example Hacker Notes page to must visit.

  = link_to image_tag("GoogleChromeLogo.png", size: "54x54"), "https://chrome.google.com/webstore/detail/hackernotes-plugin/acphikopigkpfbkonnacihkhcefdeagg"
  %p
    %span Try
    = link_to "Hacker Notes Chrome Plugin.", "https://chrome.google.com/webstore/detail/hackernotes-plugin/acphikopigkpfbkonnacihkhcefdeagg"
    %br
    %span It makes coming from Github to Hacker Notes super easy.

  %p
    = image_tag "karma.png", size: "54x54"
    %div Earn Karma for all your contributions.

app/views/home/_repo_logos.html.haml
%div.repo_logos
  %h2 Hacker - Notes - Stars
  = link_to image_tag("logos/git-logo.png"), show_repo_path(owner: 'git', name: 'git')
  = link_to image_tag("logos/node-logo.png"), show_repo_path(owner: 'joyent', name: 'node')
  = link_to image_tag("logos/python-logo.png"), show_repo_path(owner: 'python-git', name: 'python')
  = link_to image_tag("logos/mongodb-logo.png"), show_repo_path(owner: 'mongodb', name: 'mongo')
  = link_to image_tag("logos/rails-logo.png"), show_repo_path(owner: 'rails', name: 'rails')
  = link_to image_tag("logos/backbone-logo.png"), show_repo_path(owner: 'documentcloud', name: 'backbone')
  = link_to image_tag("logos/cucumber-logo.png"), show_repo_path(owner: 'cucumber', name: 'cucumber')
  = link_to image_tag("logos/emberjs-logo.png"), show_repo_path(owner: 'emberjs', name: 'ember.js')
  = link_to image_tag("logos/jasmine-logo.png"), show_repo_path(owner: 'pivotal', name: 'jasmine')

app/views/home/homepage.html.haml
= page_keywords "hacker notes, software development, web development, github, open source"
= page_description "Hacker Notes provides resources around Open Source softwares to learn curated by Github users"

= render "shared/fork", name: 'HackerNotes', owner: 'abhishek77in'

= render "news"
= render "leader_board"
= render "repo_logos"

%div.home

  %div{style: 'float: left; width: 33%'}
    <script src="https://gist.github.com/abhishek77in/5890917.js"></script>
  %div{style: 'float: left; width: 33%; margin-left: 8px;'}
    <script src="https://gist.github.com/abhishek77in/5903863.js"></script>
  %div{style: 'float: left; padding-left: 20px; width: 320px;'}
    %h4.title Popular repositories
    %ul.repo-list
      - @popular_repos.each do |r|
        %li= link_to r.name, show_repo_path(owner: r.owner, name: r.name)
    %h4.title Recently visited repositories
    %ul.repo-list
      - @repos.each do |r|
        %li= link_to r.name, show_repo_path(owner: r.owner, name: r.name)

  %div.search_form= render "shared/search_form"

  %div.copyright
    %a.twitter-follow-button{href: "https://twitter.com/HackerNotes", 'data-show-count' => "false"} Follow @HackerNotes
    %div.small
      © 
      = link_to 'hackernotes.org', root_url
      , 2013 /
      Built by:
      = link_to '@abhishek77in', 'https://twitter.com/abhishek77in'